name: Check Arxiv Daily

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-arxiv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install arxiv pandas
    - name: Run Python script
      run: python arxiv_autosearch.py
    - name: Commit and push results
      run: |
        git add.
        git commit -m "Update arxiv results"
        git push
